# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-01-06 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=1500)),
                ('paper', models.BooleanField()),
                ('electronic', models.BooleanField()),
                ('type', models.CharField(choices=[('TAB', 'Tablature'), ('PVG', 'PVG')], default='TAB', max_length=3)),
                ('comments', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1500, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
