# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-01-15 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partition',
            old_name='type',
            new_name='partitionType',
        ),
    ]
