# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_sitemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemessage',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2016, 4, 13, 21, 35, 9, 134000)),
        ),
    ]
