# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_sitemessage_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemessage',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
