# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-16 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20160413_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='sitemessage',
            name='message',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
