# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-30 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20160413_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='color',
            field=models.CharField(default='yellow', max_length=50),
        ),
    ]
