# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-16 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0003_studio_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lundi', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_when', models.DateTimeField()),
                ('activity', models.CharField(default='', max_length=250)),
                ('starting_hour', models.IntegerField(validators=[reservation.models.validate_hour])),
                ('starting_minutes', models.IntegerField(validators=[reservation.models.validate_minutes])),
                ('ending_hour', models.IntegerField(validators=[reservation.models.validate_hour])),
                ('ending_minutes', models.IntegerField(validators=[reservation.models.validate_minutes])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('studio_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Studio', verbose_name='Studio')),
                ('weekDayKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.WeekDay', verbose_name='WeekDay')),
            ],
        ),
    ]
