# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-16 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_weekday_weeklyreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyreservation',
            old_name='weekDayKey',
            new_name='weekDay_key',
        ),
    ]
