# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-12-16 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20171216_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekday',
            options={'ordering': ['id']},
        ),
    ]
